In [1]:
import numpy as np
import pandas as pd

# plots
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib notebook

In [51]:
properties = pd.read_csv('properati-AR-2017-08-01-properties-sell.csv')

In [52]:
properties.count()

id                            187482
created_on                    187482
operation                     187482
property_type                 187482
place_name                    187447
place_with_parent_names       187482
country_name                  187482
state_name                    187482
geonames_id                   158318
lat-lon                       118761
lat                           118761
lon                           118761
price                         154443
currency                      154441
price_aprox_local_currency    154443
price_aprox_usd               154443
surface_total_in_m2           125027
surface_covered_in_m2         152420
price_usd_per_m2              105024
price_per_m2                  131665
floor                          14294
rooms                          80320
expenses                       17520
properati_url                 187482
description                   187473
title                         187482
image_thumbnail               182814
dtype: int64

In [6]:
properties.dtypes

id                                    object
created_on                    datetime64[ns]
operation                             object
property_type                         object
place_name                            object
place_with_parent_names               object
country_name                          object
state_name                            object
geonames_id                          float64
lat-lon                               object
lat                                  float64
lon                                  float64
price                                float64
currency                              object
price_aprox_local_currency           float64
price_aprox_usd                      float64
surface_total_in_m2                  float64
surface_covered_in_m2                float64
price_usd_per_m2                     float64
price_per_m2                         float64
floor                                float64
rooms                                float64
expenses                             float64
properati_url                         object
description                           object
title                                 object
image_thumbnail                       object
dtype: object

In [46]:
properties.head(10)

,id,created_on,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,...,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail
0,c8a66ee9e3da083ab66dacd165e8a5cc718b1cf2,2012-09-19,sell,house,San Antonio De Padua,|Argentina|Bs.As. G.B.A. Zona Oeste|Merlo|San ...,Argentina,Bs.As. G.B.A. Zona Oeste,3429244.0,NaN,...,93.0,360.360360,1290.322581,NaN,NaN,NaN,http://www.properati.com.ar/udh_venta_casa_mer...,CASA CON LOCAL EN VENTA EN PADUA.2 DORMITORIOS...,CASA EN VENTA,https://thumbs4.properati.com/1/ufoyqwscVk8n3e...
1,a205c53378e7879cf7519659317fb410c060d20e,2012-10-22,sell,house,San Antonio De Padua,|Argentina|Bs.As. G.B.A. Zona Oeste|Merlo|San ...,Argentina,Bs.As. G.B.A. Zona Oeste,3429244.0,NaN,...,220.0,1000.000000,1000.000000,NaN,NaN,NaN,http://www.properati.com.ar/20hi_venta_casa_me...,CHALET VENTA 4 AMBIENTES PADUA.EXCELENTE CHALE...,CASA EN VENTA,https://thumbs4.properati.com/5/I5RS_jAIUseo9H...
4,9446052c949050359fb08b9f1ba83ba2eaa20c99,2012-12-08,sell,house,Mataderos,|Argentina|Capital Federal|Mataderos|,Argentina,Capital Federal,3430787.0,"-34.6544492346,-58.4895603251",...,103.0,616.666667,1796.116505,NaN,5.0,NaN,http://www.properati.com.ar/4m4m_venta_casa_ma...,Casa Multifamiliar en Mataderos!!! Sobre lote ...,CASA EN VENTA,https://thumbs4.properati.com/6/DsNJjCb5_zIPV0...
5,4d3b492ed5f9c74cdf33b56b98328e5c950e3f9c,2013-01-04,sell,apartment,Pilar,|Argentina|Bs.As. G.B.A. Zona Norte|Pilar|,Argentina,Bs.As. G.B.A. Zona Norte,3429979.0,"-34.429071,-58.795418",...,54.0,NaN,1796.296296,NaN,2.0,NaN,http://www.properati.com.ar/518a_venta_departa...,"Venta - Departamento - Argentina, Buenos Aires...",Departamento en Venta ubicado en Arcos de Pilar,https://thumbs4.properati.com/8/bJn9FqcBRGi_8H...
6,535441f569473f6e5d687c38b27d9b9c6e69e284,2013-01-09,sell,store,San Isidro,|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro|,Argentina,Bs.As. G.B.A. Zona Norte,3428983.0,"-34.4789383,-58.5214371",...,NaN,NaN,NaN,NaN,1.0,NaN,http://www.properati.com.ar/52p4_venta_local_s...,"Venta - Local - Argentina, Buenos Aires, Zona ...",Local en Venta ubicado en San Isidro,https://thumbs4.properati.com/9/ZCK2RkrsymyN5s...
10,61f3789618edabeaa7b5fc06ff36112f8a06557f,2013-01-26,sell,apartment,Pilar,|Argentina|Bs.As. G.B.A. Zona Norte|Pilar|,Argentina,Bs.As. G.B.A. Zona Norte,3429979.0,"-34.439241,-58.798589",...,45.0,NaN,2222.222222,NaN,2.0,NaN,http://www.properati.com.ar/59ec_venta_departa...,"Venta - Departamento - Argentina, Buenos Aires...",Departamento en Venta ubicado en Pilar,https://thumbs4.properati.com/5/hiXoFGFHBiIhV2...
12,e842ed22eac89b9bffff146377abfd5bceb0b0cd,2013-02-08,sell,house,Benavidez,|Argentina|Bs.As. G.B.A. Zona Norte|Tigre|Bena...,Argentina,Bs.As. G.B.A. Zona Norte,3436048.0,"-34.4029676,-58.7290677",...,375.0,NaN,1040.000000,NaN,6.0,NaN,http://www.properati.com.ar/5paq_venta_casa_be...,"Venta - Casa - Argentina, Buenos Aires, Zona N...",Casa en Venta ubicado en Benavidez,https://thumbs4.properati.com/5/CNk5CqtcxAqA4E...
13,4dcfa9a54bdd18cd5438221c6dcfa94738c11c40,2013-02-15,sell,apartment,Florida,|Argentina|Bs.As. G.B.A. Zona Norte|Vicente Ló...,Argentina,Bs.As. G.B.A. Zona Norte,3433908.0,"-34.5338458,-58.489214",...,111.0,NaN,2477.477477,NaN,4.0,NaN,http://www.properati.com.ar/5rsb_venta_departa...,"Venta - Departamento - Argentina, Buenos Aires...",Departamento en Venta ubicado en Florida,https://thumbs4.properati.com/8/lu55MpJTjFYikR...
28,c60df01c06fe62d91c4767830ee14890fa4d73ec,2013-03-23,sell,house,Haedo,|Argentina|Bs.As. G.B.A. Zona Oeste|Morón|Haedo|,Argentina,Bs.As. G.B.A. Zona Oeste,NaN,NaN,...,276.0,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/6iiy_venta_casa_moron,VENTA CASA 5 AMBIENTES EN HAEDO.Chalet sobre l...,CASA EN VENTA,https://thumbs4.properati.com/8/3iYq-462PptY1E...
29,0f0e301809a14b8c069b267fa1c56a3b5ec35d9e,2013-03-23,sell,apartment,Ramos Mejía,|Argentina|Bs.As. G.B.A. Zona Oeste|La Matanza...,Argentina,Bs.As. G.B.A. Zona Oeste,3429617.0,NaN,...,60.0,1466.666667,1466.666667,1.0,2.0,200.0,http://www.properati.com.ar/6iiz_venta_departa...,VENTA DEPARTAMENTO 2 AMBIENTES EN RAMOS MEJÍA....,DEPARTAMENTO EN VENTA,https://thumbs4.properati.com/0/y0AjbI5mdYmcrt...

In [58]:
# Convierto la columna de fecha en un datetime.
properties.created_on = pd.to_datetime(properties.created_on)

In [59]:
# Filtro los resultados que no son de caba.
properties = properties.loc[properties['state_name'].isin(['Capital Federal', 'Bs.As. G.B.A. Zona Sur','Bs.As. G.B.A. Zona Norte','Bs.As. G.B.A. Zona Oeste'])]

In [56]:
#Remuevo todos los registros con precio 0
properties = properties[properties.price>0]

In [60]:
properties.count()

id                            110202
created_on                    110202
operation                     110202
property_type                 110202
place_name                    110168
place_with_parent_names       110202
country_name                  110202
state_name                    110202
geonames_id                    85698
lat-lon                        66185
lat                            66185
lon                            66185
price                         110202
currency                      110202
price_aprox_local_currency    110202
price_aprox_usd               110202
surface_total_in_m2            79373
surface_covered_in_m2          98875
price_usd_per_m2               79107
price_per_m2                   98873
floor                          10099
rooms                          43556
expenses                       14140
properati_url                 110202
description                   110195
title                         110202
image_thumbnail               107733
dtype: int64

In [66]:
properties.price.describe()

count    1.102020e+05
mean     3.575582e+05
std      8.248399e+05
min      5.000000e+03
25%      1.050000e+05
50%      1.740000e+05
75%      3.400000e+05
max      1.000000e+08
Name: price, dtype: float64

In [67]:
grouped_by_parent_names = properties.groupby('place_name')
grouped_by_parent_names.describe()['price']['count'].describe()

count     560.000000
mean      196.728571
std       510.120065
min         1.000000
25%         3.000000
50%        16.000000
75%       116.750000
max      4494.000000
Name: count, dtype: float64

In [69]:
list(grouped_by_place)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.